### ISSUE TITLE
How to disable log files

### ISSUE THREAD

**Issue by exxpploit** [maxludden/MaxGradient#13]
I'm very sorry, but I haven't found a way to disable the standard log files anywhere. they are empty and just interfere with my code logic, please help me turn it off
![image](https://github.com/user-attachments/assets/5ba63b45-c66f-4202-a0e8-446f95f728ad)

**Comment by maxludden** [comment]
I totally get how that could be very annoying. First off, thanks for you using rich-gradient🌈! Can I ask what version you're using? I completely took the logging out of rich gradient a week or two ago as I was having the same annoyance.

I just double checked the code and their were still a few references that i'd missed (apologies), which I'm removing now and will push the fix. But I'm hoping that simply updating to the most recent release will resolve your issue. If this isn't the case, please let me know, and I'll deep dive what is causing the issue after work.
